version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade aws-sam-cli
  build:
    commands:
      - sam build
      - sam package --s3-bucket manuel-lillo-cloudx-cf-bucket --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml
    - .aws-sam/**/*